CREATE TABLE IF NOT EXISTS PENDING_ORDER ( ORDER_ID BIGINT,
	INSTRUMENT CHAR(7),
	ACTION VARCHAR(5),
	UNITS INTEGER,
	STOP_ENTRY FLOAT,
	TARGET_PROFIT FLOAT,
	STOP_LOSS FLOAT,
	TRIGGER_DISTANCE_PIPS TINYINT );
	